### ISSUE TITLE
Create simple footer

### ISSUE THREAD

**Issue by ghost** [Garrison88/tomkat-creative#1]
Footer works in either a page that extends beyond the window or a page that doesn't, but not both. Cannot figure out how to get the footer to stay at the bottom of every page without overlapping the content. Footer is located in the footer.ejs partial under /views/partials

**Comment by radiant-kal** [comment]
Did you want a fixed footer or something that you have to scroll down to?

**Comment by ghost** [comment]
Something to scroll down to

**Comment by ghost** [comment]
Clear fix
